[workspace]
members = [".", "ffi", "ffi/common", "ffi/ruby", "ffi/python"]
resolver = "3"

[package]
name = "github-mock-api"
version = "0.1.0"
edition = "2024"

[lints.clippy]
expect_used = "deny"
indexing_slicing = "deny"
panic = "deny"
panic_in_result_fn = "deny"
todo = "deny"
unimplemented = "deny"
unreachable = "deny"
unwrap_in_result = "deny"
unwrap_used = "deny"

[dependencies]
clap = { version = "4", features = ["derive"] }
axum = "0.8"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net", "signal"] }
tracing = "0.1"
tracing-subscriber = "0.3"
thiserror = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
reqwest = { version = "0.13", default-features = false, features = ["json"] }
